


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."handle_times"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
    BEGIN
    IF (TG_OP = 'INSERT') THEN
        NEW.created_at := now();
        NEW.updated_at := now();
    ELSEIF (TG_OP = 'UPDATE') THEN
        NEW.created_at = OLD.created_at;
        NEW.updated_at = now();
    END IF;
    RETURN NEW;
    END;
    $$;


ALTER FUNCTION "public"."handle_times"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."COMMUNITY" (
    "COMMUNITY_ID" bigint NOT NULL,
    "LOCATION_NAME" character varying NOT NULL,
    "PRICE_RATE" double precision,
    "MANAGER_ID" bigint
);


ALTER TABLE "public"."COMMUNITY" OWNER TO "postgres";


ALTER TABLE "public"."COMMUNITY" ALTER COLUMN "COMMUNITY_ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Community_COMMUNITY_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."METERS" (
    "HOUSEHOLD_NAME" "text" NOT NULL,
    "METER_ID" smallint NOT NULL,
    "COMMUNITY_ID" smallint,
    "ACTIVE" boolean,
    "LAST_READ_DATE" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text"),
    "LATEST_READING" bigint
);


ALTER TABLE "public"."METERS" OWNER TO "postgres";


COMMENT ON TABLE "public"."METERS" IS 'All existing water meters';



ALTER TABLE "public"."METERS" ALTER COLUMN "METER_ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."METERS_METER_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."METER_READINGS" (
    "METER_ID" bigint NOT NULL,
    "CURRENT_READING" bigint,
    "WATER_USED" bigint,
    "PRICE" double precision,
    "DATE_LAST_READ" timestamp with time zone,
    "DATE_CURRENT" timestamp with time zone,
    "LAST_READING" bigint,
    "entry_id" smallint NOT NULL
);


ALTER TABLE "public"."METER_READINGS" OWNER TO "postgres";


ALTER TABLE "public"."METER_READINGS" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."METER_READINGS_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."METER_READINGS" ALTER COLUMN "METER_ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Meters_METER_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."WATER_MANAGERS" (
    "USER_ID" bigint NOT NULL,
    "USERNAME" character varying NOT NULL,
    "PASSWORD" character varying,
    "LOCATION_ID" bigint
);


ALTER TABLE "public"."WATER_MANAGERS" OWNER TO "postgres";


ALTER TABLE "public"."WATER_MANAGERS" ALTER COLUMN "USER_ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."WATER_MANAGERS_USER_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."COMMUNITY"
    ADD CONSTRAINT "Community_pkey" PRIMARY KEY ("COMMUNITY_ID");



ALTER TABLE ONLY "public"."METERS"
    ADD CONSTRAINT "METERS_METER_ID_key" UNIQUE ("METER_ID");



ALTER TABLE ONLY "public"."METERS"
    ADD CONSTRAINT "METERS_pkey" PRIMARY KEY ("HOUSEHOLD_NAME");



ALTER TABLE ONLY "public"."METER_READINGS"
    ADD CONSTRAINT "METER_READINGS_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."WATER_MANAGERS"
    ADD CONSTRAINT "WATER_MANAGERS_pkey" PRIMARY KEY ("USER_ID");



ALTER TABLE "public"."COMMUNITY" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable insert for authenticated users only" ON "public"."WATER_MANAGERS" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "INSERT" ON "public"."METERS" FOR INSERT WITH CHECK (true);



ALTER TABLE "public"."METERS" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."METER_READINGS" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Public insert into Meters" ON "public"."METER_READINGS" FOR INSERT WITH CHECK (true);



CREATE POLICY "READ" ON "public"."METERS" FOR SELECT USING (true);



CREATE POLICY "Read Community" ON "public"."COMMUNITY" FOR SELECT USING (true);



CREATE POLICY "UPDATE" ON "public"."METERS" FOR UPDATE USING (true);



ALTER TABLE "public"."WATER_MANAGERS" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "default" ON "public"."METER_READINGS" FOR SELECT USING (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."METERS";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."METER_READINGS";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."handle_times"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_times"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_times"() TO "service_role";


















GRANT ALL ON TABLE "public"."COMMUNITY" TO "anon";
GRANT ALL ON TABLE "public"."COMMUNITY" TO "authenticated";
GRANT ALL ON TABLE "public"."COMMUNITY" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Community_COMMUNITY_ID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Community_COMMUNITY_ID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Community_COMMUNITY_ID_seq" TO "service_role";



GRANT ALL ON TABLE "public"."METERS" TO "anon";
GRANT ALL ON TABLE "public"."METERS" TO "authenticated";
GRANT ALL ON TABLE "public"."METERS" TO "service_role";



GRANT ALL ON SEQUENCE "public"."METERS_METER_ID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."METERS_METER_ID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."METERS_METER_ID_seq" TO "service_role";



GRANT ALL ON TABLE "public"."METER_READINGS" TO "anon";
GRANT ALL ON TABLE "public"."METER_READINGS" TO "authenticated";
GRANT ALL ON TABLE "public"."METER_READINGS" TO "service_role";



GRANT ALL ON SEQUENCE "public"."METER_READINGS_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."METER_READINGS_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."METER_READINGS_entry_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Meters_METER_ID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Meters_METER_ID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Meters_METER_ID_seq" TO "service_role";



GRANT ALL ON TABLE "public"."WATER_MANAGERS" TO "anon";
GRANT ALL ON TABLE "public"."WATER_MANAGERS" TO "authenticated";
GRANT ALL ON TABLE "public"."WATER_MANAGERS" TO "service_role";



GRANT ALL ON SEQUENCE "public"."WATER_MANAGERS_USER_ID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."WATER_MANAGERS_USER_ID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."WATER_MANAGERS_USER_ID_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


